version: '3'

services:
  eyealertbackend:
    build: eyealertbackend
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://eye_alert:3306/eyealert?createDatabaseIfNotExist=true
      DB_USER_NAME: root
      DB_PASSWORD: admin
    restart: always
    depends_on:
      eye_alert:
          condition: service_healthy
  eye_alert:
    image: mysql:9.1.0 
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: eyealert
      TZ: America/Lima
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10