
CREATE TABLE mae_roles(
	rol_id int not null auto_increment,
    descripcion varchar(20) not null,
    primary key(rol_id)
);

create table mae_usuarios (
	usuario_id int not null auto_increment,
    nombres varchar(100) not null,
    apellidos varchar(100) not null,
    email varchar(255) not null unique,
    password varchar(50) not null,
    cuestionario_conocimientos_completado tinyint(1) not null default 0,
    rol_id int not null,
	fecha datetime not null default current_timestamp,
    primary key (usuario_id),
    foreign key (rol_id) references mae_roles(rol_id)
);

CREATE TABLE TRS_EVALUACIONES(
	EVALUACION_ID INT AUTO_INCREMENT,
    FECHA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TIEMPO_PREDICCION DECIMAL(9,2) NOT NULL,
    RESULTADO TINYINT(1) NOT NULL,
    RESULTADO_ACERTADO TINYINT(1),
    USUARIO_ID INT NOT NULL,
    PRIMARY KEY(EVALUACION_ID),
    FOREIGN KEY(USUARIO_ID) references MAE_USUARIOS(USUARIO_ID)
);

CREATE TABLE MAE_PREGUNTAS(
	PREGUNTA_ID INT NOT NULL AUTO_INCREMENT,
    DESCRIPCION VARCHAR(255) NOT NULL,
    ESTADO TINYINT(1) NOT NULL DEFAULT 1,
    PRIMARY KEY(PREGUNTA_ID)
);

CREATE TABLE MAE_RESPUESTAS(
	RESPUESTA_ID INT NOT NULL AUTO_INCREMENT,
    DESCRIPCION VARCHAR(20) NOT NULL UNIQUE,
    PRIMARY KEY(RESPUESTA_ID)
);

CREATE TABLE TRS_PREGUNTA_DETALLE(
    PREGUNTA_ID INT NOT NULL,
    RESPUESTA_ID INT NOT NULL,
    PRIMARY KEY(PREGUNTA_ID, RESPUESTA_ID),
    FOREIGN KEY(PREGUNTA_ID) references MAE_PREGUNTAS(PREGUNTA_ID),
    FOREIGN KEY(RESPUESTA_ID) references MAE_RESPUESTAS(RESPUESTA_ID)
);

CREATE TABLE TRD_DETALLE_EVALUACION(
	DETALLE_EVALUACION_ID INT NOT NULL AUTO_INCREMENT,
	EVALUACION_ID INT NOT NULL,
    PREGUNTA_ID INT NOT NULL,
    RESPUESTA_ID INT NULL,
    RESPUESTA_TEXTO VARCHAR(3),
    PRIMARY KEY(DETALLE_EVALUACION_ID),
    FOREIGN KEY(EVALUACION_ID) references TRS_EVALUACIONES(EVALUACION_ID),
    FOREIGN KEY(PREGUNTA_ID) references MAE_PREGUNTAS(PREGUNTA_ID),
    FOREIGN KEY(RESPUESTA_ID) references MAE_RESPUESTAS(RESPUESTA_ID)
);

CREATE TABLE MAE_DATOS_INFORMATIVOS(
	DATO_INFORMATIVO_ID INT NOT NULL AUTO_INCREMENT,
    TITULO VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(255) NOT NULL,
    FUENTE LONGTEXT NOT NULL,
    FUENTE_MULTIMEDIA LONGTEXT,
    PRIMARY KEY(DATO_INFORMATIVO_ID)
);

CREATE TABLE CUESTIONARIO_CONOCIMIENTOS(
	CUESTIONARIO_CONOCIMIENTOS_ID INT NOT NULL AUTO_INCREMENT,    
	FECHA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	USUARIO_ID INT NOT NULL,
    PUNTAJE_OBTENIDO INT NOT NULL,
    PRIMARY KEY(CUESTIONARIO_CONOCIMIENTOS_ID),
    FOREIGN KEY(USUARIO_ID) references MAE_USUARIOS(USUARIO_ID)
);

CREATE TABLE RESPUESTA_CUESTIONARIO_CONOCIMIENTOS(
	RESPUESTA_CUESTIONARIO_CONOCIMIENTOS_ID INT NOT NULL AUTO_INCREMENT,
    CUESTIONARIO_CONOCIMIENTOS_ID INT NOT NULL,
    PREGUNTA LONGTEXT NOT NULL,
    RESPUESTA VARCHAR(1) NOT NULL,
    PUNTAJE_PREGUNTA TINYINT(1) NOT NULL,
    PRIMARY KEY(RESPUESTA_CUESTIONARIO_CONOCIMIENTOS_ID),
    FOREIGN KEY(CUESTIONARIO_CONOCIMIENTOS_ID) references CUESTIONARIO_CONOCIMIENTOS(CUESTIONARIO_CONOCIMIENTOS_ID)
);

CREATE TABLE CONFIG_CUESTIONARIO(
	CONFIG_CUESTIONARIO_ID INT NOT NULL AUTO_INCREMENT,
    DIAS_ESPERA INT NOT NULL,
    PRIMARY KEY(CONFIG_CUESTIONARIO_ID)
)
