CREATE DATABASE eyealert;

use eyealert;

CREATE TABLE MAE_ROLES(
	ROL_ID INT NOT NULL AUTO_INCREMENT,
    DESCRIPCION VARCHAR(20) NOT NULL,
    PRIMARY KEY(ROL_ID)
);

CREATE TABLE MAE_USUARIOS(
	USUARIO_ID INT AUTO_INCREMENT,
    NOMBRES VARCHAR(100) NOT NULL,
    APELLIDOS VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL,
    ROL_ID INT NOT NULL,
    PRIMARY KEY(USUARIO_ID),
    FOREIGN KEY(ROL_ID) REFERENCES MAE_ROLES(ROL_ID)
);

CREATE TABLE TRS_EVALUACIONES(
	EVALUACION_ID INT AUTO_INCREMENT,
    FECHA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TIEMPO_PREDICCION DECIMAL(9,2) NOT NULL,
    RESULTADO TINYINT(1) NOT NULL,
    USUARIO_ID INT NOT NULL,
    PRIMARY KEY(EVALUACION_ID),
    FOREIGN KEY(USUARIO_ID) references MAE_USUARIOS(USUARIO_ID)
);

CREATE TABLE MAE_PREGUNTAS(
	PREGUNTA_ID INT NOT NULL AUTO_INCREMENT,
    DESCRIPCION VARCHAR(255) NOT NULL,
    ESTADO TINYINT(1) NOT NULL DEFAULT 1,
    PRIMARY KEY(PREGUNTA_ID)
);

CREATE TABLE MAE_RESPUESTAS(
	RESPUESTA_ID INT NOT NULL AUTO_INCREMENT,
    DESCRIPCION VARCHAR(20) NOT NULL UNIQUE,
    PRIMARY KEY(RESPUESTA_ID)
);

CREATE TABLE TRS_PREGUNTA_DETALLE(
    PREGUNTA_ID INT NOT NULL,
    RESPUESTA_ID INT NOT NULL,
    PRIMARY KEY(PREGUNTA_ID, RESPUESTA_ID),
    FOREIGN KEY(PREGUNTA_ID) references MAE_PREGUNTAS(PREGUNTA_ID),
    FOREIGN KEY(RESPUESTA_ID) references MAE_RESPUESTAS(RESPUESTA_ID)
);

CREATE TABLE TRD_DETALLE_EVALUACION(
	DETALLE_EVALUACION_ID INT NOT NULL AUTO_INCREMENT,
	EVALUACION_ID INT NOT NULL,
    PREGUNTA_ID INT NOT NULL,
    RESPUESTA_ID INT NULL,
    RESPUESTA_TEXTO VARCHAR(3),
    PRIMARY KEY(DETALLE_EVALUACION_ID),
    FOREIGN KEY(EVALUACION_ID) references TRS_EVALUACIONES(EVALUACION_ID),
    FOREIGN KEY(PREGUNTA_ID) references MAE_PREGUNTAS(PREGUNTA_ID),
    FOREIGN KEY(RESPUESTA_ID) references MAE_RESPUESTAS(RESPUESTA_ID)
);

CREATE TABLE MAE_DATOS_INFORMATIVOS(
	DATO_INFORMATIVO_ID INT NOT NULL AUTO_INCREMENT,
    TITULO VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(255) NOT NULL,
    FUENTE LONGTEXT NOT NULL,
    FUENTE_MULTIMEDIA LONGTEXT,
    PRIMARY KEY(DATO_INFORMATIVO_ID)
);